#!/usr/bin/env python3
# Characterisation suite for the analyzer worker's analyze(): pins what TODAY's
# worker returns for a set of generated tracks, so the planned split of the
# acoustic pass into facets (head / loudness / tail / clap / vocal / stems) can
# be refactored underneath it and proven to change nothing.
#
# This is a SNAPSHOT test, not a statement that today's numbers are right.
# Several rows deliberately pin known limitations, so a refactor that changes
# them must do so on purpose (and update the snapshot in the same commit):
#   * capped_flac: a byte-capped download (complete=False) has NO tail fields
#     and no outro: the reason ~half of a real library never gets a dead-air
#     trim at the end.
#   * long_tail_silence: a 25 s silent ending fills the whole 20 s tail
#     window, so the gap is unmeasurable and omitted.
#   * quiet_intro / lead_silence_4s: loudness, peak, sections and pace are
#     measured over the first ANALYZE_SECONDS (40 s) only, not the whole track.
#
# NOT covered: CLAP and Demucs (heavy image only, and CLAP's feature extractor
# crops a RANDOM 10 s of each window with laion/clap-htsat-unfused, so its
# vector isn't reproducible run to run), and the network fetch (fetch_audio).
#
# Needs the analyzer runtime: librosa 0.11 / soundfile / pyloudnorm / numpy
# and ffmpeg (with libmp3lame) on PATH. That is why it is NOT in the
# analyzer-python.test.ts shim (that shim only runs dependency-light suites).
# Run it inside the analyzer image, from the repo root:
#
#   docker run --rm -v "$PWD/controller/scripts:/w:ro" -e PYTHONDONTWRITEBYTECODE=1 \
#     --entrypoint /opt/analyzer/venv/bin/python ghcr.io/perminder-klair/subwave-analyzer:latest \
#     /w/analyzer_characterisation_test.py
#
# or any venv with the same pins: `python analyzer_characterisation_test.py`.
# `--update` rewrites the snapshot; `--keep DIR` keeps the generated audio.
# Exit 0 = matches the snapshot within tolerance, 1 = drift (diff printed).
#
# Tolerances: the fixtures are generated by numpy + ffmpeg at run time, and an
# ffmpeg/numpy/numba upgrade may move decoder output by a few samples. Times
# are compared within TOL_MS, rates/levels within small absolute bounds,
# strings, keys and list lengths exactly. A real behaviour change (a field
# appearing or disappearing, a key changing, a gap moving by a frame or more)
# still fails.

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPSHOT = os.path.join(HERE, "fixtures", "analyzer-characterisation", "snapshot.json")

# Keep the run lean and deterministic regardless of the caller's environment.
for k in ("ANALYZE_AUDIO_EMBEDDING", "ANALYZE_VOCAL_ACTIVITY", "ANALYZE_SECONDS",
          "ANALYZE_OUTRO_SECONDS", "ANALYZE_SILENCE_DBFS", "ANALYZE_SR", "ANALYZE_MAX_BYTES"):
    os.environ.pop(k, None)

try:
    import numpy as np
    import librosa
except ImportError as e:
    print(f"FAIL: analyzer runtime required ({e}); run inside the analyzer image, see header")
    sys.exit(1)
if not shutil.which("ffmpeg"):
    print("FAIL: ffmpeg is required on PATH")
    sys.exit(1)

sys.path.insert(0, HERE)
import analyze_worker as aw  # noqa: E402

SR = 44100
TOL_MS = 30          # < one analysis frame (2048 samples @ 22.05 kHz = 93 ms)
TOL = {
    "bpm": 0.5,
    "confidence": 0.02,
    "loudness_lufs": 0.2,
    "peak_db": 0.2,
    "lufs": 0.2,
    "value": 0.02,      # pace curve values (normalised 0..1)
}
CAP_BYTES = 12 * 1024 * 1024   # the analyzer's default ANALYZE_MAX_BYTES


# ------------------------------------------------------------------ audio --
def _music(sec, seed, bpm=124.0, level=1.0):
    """Deterministic 'music': a kick on every beat, a moving bass line and band
    noise, so beat tracking, chroma and loudness all have something to bite."""
    rng = np.random.default_rng(seed)
    n = int(sec * SR)
    t = np.arange(n) / SR
    beat = 60.0 / bpm
    kick = np.sin(2 * np.pi * 55 * t) * np.exp(-((t % beat) / 0.05))
    root = 110.0 * 2 ** (np.floor(t / (beat * 8)) % 4 * 2 / 12)   # i - ii - iii - iv every 2 bars
    bass = 0.35 * np.sin(2 * np.pi * root * t)
    hats = np.convolve(rng.standard_normal(n), [1, -1], mode="same") * 0.05 * ((t % (beat / 2)) < 0.03)
    pad = 0.12 * (np.sin(2 * np.pi * 220 * t) + np.sin(2 * np.pi * 277.18 * t) + np.sin(2 * np.pi * 329.63 * t))
    mono = (0.6 * kick + bass + hats + pad) * level
    return np.stack([mono, np.roll(mono, 23) * 0.95], axis=1)


def _silence(sec):
    return np.zeros((int(sec * SR), 2))


def _noise_music(sec, seed):
    """Dense, poorly-compressible content so a FLAC of it is large."""
    rng = np.random.default_rng(seed)
    x = _music(sec, seed)
    return x + 0.25 * rng.standard_normal(x.shape)


def _write(path, x, codec_args):
    peak = np.max(np.abs(x)) or 1.0
    pcm = (x / peak * 0.89 * 32767).astype("<i2")  # ~ -1 dBFS
    wav = path + ".src.wav"
    import wave
    with wave.open(wav, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", wav, *codec_args, path], check=True)
    os.remove(wav)


def build_fixtures(d):
    """name -> (path, analyze kwargs). Every file is generated, never committed."""
    fx = {}

    def add(name, x, ext, codec, **kw):
        p = os.path.join(d, f"{name}.{ext}")
        _write(p, x, codec)
        fx[name] = (p, kw)
        return p

    flac = ["-c:a", "flac", "-compression_level", "5"]
    mp3 = ["-c:a", "libmp3lame", "-b:a", "192k"]

    # Beat grid / BPM / key on a clean 120 BPM track with no silence anywhere.
    add("click_120", _music(90, 1, bpm=120.0), "flac", flac, complete=True)
    # Ending gaps: none, short, and longer than the 20 s tail window.
    add("tail_3s", np.vstack([_music(60, 2), _silence(3)]), "flac", flac, complete=True)
    add("long_tail_silence", np.vstack([_music(60, 3), _silence(25)]), "flac", flac, complete=True)
    # Leading dead air vs a quiet-but-audible intro (absolute floor, not relative).
    add("lead_silence_4s", np.vstack([_silence(4), _music(50, 4), _silence(2)]), "flac", flac, complete=True)
    add("quiet_intro", np.vstack([_music(15, 5, level=0.03), _music(45, 5), _silence(2)]), "flac", flac, complete=True)
    # A FLAC over the 12 MiB download cap: full file vs today's capped download.
    big = add("big_flac", np.vstack([_noise_music(150, 6), _silence(5)]), "flac", flac, complete=True)
    if os.path.getsize(big) <= CAP_BYTES:
        raise RuntimeError(f"big_flac is only {os.path.getsize(big)} bytes; must exceed the 12 MiB cap")
    capped = os.path.join(d, "capped_flac.flac")
    with open(big, "rb") as src, open(capped, "wb") as dst:
        dst.write(src.read(CAP_BYTES))
    fx["capped_flac"] = (capped, {"complete": False})
    # MP3 with junk before the first frame (libsndfile can't open it: the
    # ensure_fast_decode pre-decode path, issue #1073).
    p = add("mp3_plain", np.vstack([_music(70, 7), _silence(4)]), "mp3", mp3, complete=True)
    junk = os.path.join(d, "mp3_junk_prefix.mp3")
    with open(p, "rb") as src, open(junk, "wb") as dst:
        dst.write(np.random.default_rng(8).integers(0, 255, 3000, dtype=np.uint8).tobytes())
        dst.write(src.read())
    fx["mp3_junk_prefix"] = (junk, {"complete": True})
    # Shorter than the head + tail windows together.
    add("short_8s", _music(8, 9), "flac", flac, complete=True)
    # Unknown completeness (old controller callers send no flag).
    fx["tail_3s_complete_unknown"] = (fx["tail_3s"][0], {"complete": None})
    return fx


# -------------------------------------------------------------- compare --
def _close(a, b, key):
    if isinstance(a, bool) or isinstance(b, bool) or a is None or b is None:
        return a == b
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        if key.lower().endswith("ms") or key == "_ms_list":   # *_ms, startMs/endMs, beat/bar lists
            return abs(a - b) <= TOL_MS
        return abs(a - b) <= TOL.get(key, 1e-6)
    return a == b


def diff(expected, actual, path="", key=""):
    """List of human-readable differences (empty = match within tolerance)."""
    out = []
    if isinstance(expected, dict) and isinstance(actual, dict):
        for k in sorted(set(expected) | set(actual)):
            p = f"{path}.{k}" if path else k
            if k not in actual:
                out.append(f"{p}: missing (expected {json.dumps(expected[k])[:80]})")
            elif k not in expected:
                out.append(f"{p}: unexpected new field ({json.dumps(actual[k])[:80]})")
            else:
                out += diff(expected[k], actual[k], p, k)
    elif isinstance(expected, list) and isinstance(actual, list):
        if len(expected) != len(actual):
            out.append(f"{path}: length {len(actual)} != {len(expected)}")
        else:
            # beats / bars are plain lists of milliseconds
            elem_key = "_ms_list" if key in ("beats", "bars") else key
            for i, (e, a) in enumerate(zip(expected, actual)):
                out += diff(e, a, f"{path}[{i}]", elem_key)
    elif not _close(expected, actual, key):
        out.append(f"{path}: {actual!r} != {expected!r}")
    return out


# ----------------------------------------------------------------- main --
def runtime_versions():
    import soundfile
    v = {"librosa": librosa.__version__, "numpy": np.__version__, "soundfile": soundfile.__version__}
    try:
        import pyloudnorm  # noqa: F401
        v["pyloudnorm"] = getattr(pyloudnorm, "__version__", "present")
    except ImportError:
        v["pyloudnorm"] = None
    first = subprocess.run(["ffmpeg", "-version"], capture_output=True, text=True).stdout.splitlines()[:1]
    v["ffmpeg"] = first[0] if first else "?"
    return v


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--update", action="store_true", help="rewrite the snapshot from this run")
    ap.add_argument("--keep", help="keep the generated audio in this directory")
    ap.add_argument("--only", help="comma-separated fixture names")
    a = ap.parse_args()

    workdir = a.keep or tempfile.mkdtemp(prefix="sw-characterise-")
    os.makedirs(workdir, exist_ok=True)
    try:
        fixtures = build_fixtures(workdir)
        names = a.only.split(",") if a.only else list(fixtures)
        results = {}
        for name in names:
            path, kw = fixtures[name]
            # embed=False / vocal=False: lean pass, no CLAP or Demucs even on a heavy image.
            results[name] = aw.analyze(librosa, path=path, embed=False, vocal=False, **kw)
            print(f"  analysed {name}: {sorted(results[name])}")

        if a.update:
            os.makedirs(os.path.dirname(SNAPSHOT), exist_ok=True)
            doc = {"_runtime": runtime_versions(), "results": results}
            if a.only and os.path.exists(SNAPSHOT):
                old = json.load(open(SNAPSHOT))
                old["results"].update(results)
                old["_runtime"] = doc["_runtime"]
                doc = old
            with open(SNAPSHOT, "w") as f:
                json.dump(doc, f, indent=1, sort_keys=True)
                f.write("\n")
            print(f"snapshot written: {SNAPSHOT}")
            return 0

        if not os.path.exists(SNAPSHOT):
            print(f"FAIL: no snapshot at {SNAPSHOT}; run with --update first")
            return 1
        snap = json.load(open(SNAPSHOT))
        failures = 0
        for name in names:
            if name not in snap["results"]:
                print(f"  ✗ {name}: not in snapshot")
                failures += 1
                continue
            d = diff(snap["results"][name], results[name])
            if d:
                failures += 1
                print(f"  ✗ {name}")
                for line in d[:25]:
                    print(f"      {line}")
                if len(d) > 25:
                    print(f"      … {len(d) - 25} more")
            else:
                print(f"  ✓ {name}")
        if failures:
            print(f"\n{failures} fixture(s) drifted. Snapshot runtime: {snap.get('_runtime')}\n"
                  f"This runtime: {runtime_versions()}")
            return 1
        print("✓ analyzer characterisation matches the snapshot")
        return 0
    finally:
        if not a.keep:
            shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
